###############################################################################
# Cloudflare DNS
###############################################################################


---


- name: "Set Cloudflare DNS"
  hosts: all
  become: true
  vars_files:
    - ../variables.yml
  tasks:

  - name: "Create a Cloudflare DNS"
    community.general.cloudflare_dns:
      zone: "{{ item.zone }}"
      record: "{{ item.record }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
      proxied: "{{ item.proxied }}"
      account_email: "{{ cloudflare_account_email }}"
      account_api_key: "{{ cloudflare_account_api_key }}"
      state: present
    with_items: "{{ cloudflare_dns }}"


###############################################################################