###############################################################################
# PLBLISH CHROME EXTENSION AND FIREFOX EXTENSION
###############################################################################

name: Publish


###############################################################################
# ON
###############################################################################

on:
  push:
    tags:
      - '*'


###############################################################################
# JOBS
###############################################################################

jobs:

  build:

    name: Publish web extensions (Chrome & firefox) and release in github
    runs-on: ubuntu-latest
    permissions:
      contents: write

    ###########################################################################
    # STEPS
    ###########################################################################

    steps:

      #########################################################################
      # INIT & BUILD PKG
      #########################################################################
      - name: checks-out repository
        uses: actions/checkout@v3


      #########################################################################
      # IF IS IN MAIN BRANCH
      #########################################################################

      # - name: Exit if not on MAIN branch
      #   if: endsWith(github.ref, 'main') == false
      #   run: exit -1


      #########################################################################
      # BUILD PKG
      #########################################################################

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install

      - name: Install pkg dependencies
        run: |
          pnpm install
          pnpm build


      #########################################################################
      # GET PKG INFO
      #########################################################################

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1


      #########################################################################
      # GITHUB RELEASE
      #########################################################################

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/execs/*"
          body: |
            🧩 View changelog at: https://github.com/pigeonposse/{{pp_template_name}}/blob/main/CHANGELOG.md
            📜 View license: https://github.com/pigeonposse/{{pp_template_name}}/blob/main/LICENSE


############################################################################### 